theme: minima
title: Dude Blog
author: The Dude
description: > # this means to ignore newlines until "baseurl:"
  How do I dude?

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  Cowgrrl # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
